### ISSUE TITLE
vulnerable libraries pulled in as dependencies

### ISSUE THREAD

**Issue by mkj28** [thrackle/express-zip#16]
https://app.snyk.io/test/npm/express-zip/2.0.1

zip-stream 0.5.0 is 5 years old, latest is 2.1.2

**Comment by thrackle** [comment]
Hello, @mkj28.  Thanks for the nudge.  I've published a new version of this package, 3.0.0:

https://www.npmjs.com/package/express-zip/v/3.0.0

As part of the changes in that release, I dropped support for deprecated versions of node and then was able to bump zip-stream to `^2.1.2`.
