### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JuliusSenkus** [thrackle/express-zip#8]
Hi, first great job and thanks, but just wanted to mention that you should update documentation a little bit, just tell that second parameter is file name, I found it in only in source code, if I missed it somewhere sorry :)

**Comment by MadLittleMods** [comment]
It looks like this is documented now https://github.com/thrackle/express-zip/blob/07ca4acce0835e164d202fdd474ca85914ce8b70/README.md#full-api

**Comment by thrackle** [comment]
Indeed, thanks @MadLittleMods.  And thanks @JuliusSenkus for the kind words and initial report!
